indentation + revert default directory

diff --git a/install b/install
--- a/install
+++ b/install
@@ -9,13 +9,15 @@ update_config=2
 binary_arch=
 allow_legacy=
 shells="bash zsh fish"
-config_dir=~/.config/fzf
+config_base=~/.
 fish_dir=~/.config/fish
-if [[ -v XDG_CONFIG_HOME ]] && [ ! -z $XDG_CONFIG_HOME ] && [ -d $XDG_CONFIG_HOME ]; then
-    config_dir=$XDG_CONFIG_HOME/fzf
-    fish_dir=$XDG_CONFIG_HOME/fish
+if [[ -v XDG_CONFIG_HOME ]] && [[ ! -z $XDG_CONFIG_HOME ]] && [[ -d $XDG_CONFIG_HOME ]]; then
+  config_base=$XDG_CONFIG_HOME/fzf/
+  fish_dir=$XDG_CONFIG_HOME/fish/
+  mkdir -p $config_base
+elif [[ -d ~/.config/fzf ]]; then
+  config_base=~/.config/fzf/
 fi
-mkdir -p $config_dir
 
 help() {
   cat << EOF
@@ -247,8 +249,8 @@ fi
 echo
 for shell in $shells; do
   [[ "$shell" = fish ]] && continue
-  echo -n "Generate ${config_dir}/fzf.$shell ... "
-  src=${config_dir}/fzf.${shell}
+  echo -n "Generate ${config_base}fzf.$shell ... "
+  src=${config_base}fzf.${shell}
 
   fzf_completion="[[ \$- == *i* ]] && source \"$fzf_base/shell/completion.${shell}\" 2> /dev/null"
   if [ $auto_completion -eq 0 ]; then
@@ -288,13 +290,13 @@ if [[ "$shells" =~ fish ]]; then
 EOF
   [ $? -eq 0 ] && echo "OK" || echo "Failed"
 
-  mkdir -p $fish_dir/functions
-  if [ -e $fish_dir/functions/fzf.fish ]; then
-    echo -n "Remove unnecessary $fish_dir/functions/fzf.fish ... "
-    rm -f $fish_dir/functions/fzf.fish && echo "OK" || echo "Failed"
+  mkdir -p ${fish_dir}functions
+  if [ -e ${fish_dir}functions/fzf.fish ]; then
+    echo -n "Remove unnecessary ${fish_dir}functions/fzf.fish ... "
+    rm -f ${fish_dir}functions/fzf.fish && echo "OK" || echo "Failed"
   fi
 
-  fish_binding=$fish_dir/functions/fzf_key_bindings.fish
+  fish_binding=${fish_dir}functions/fzf_key_bindings.fish
   if [ $key_bindings -ne 0 ]; then
     echo -n "Symlink $fish_binding ... "
     ln -sf "$fzf_base/shell/key-bindings.fish" \
@@ -360,11 +362,11 @@ echo
 for shell in $shells; do
   [[ "$shell" = fish ]] && continue
   [ $shell = zsh ] && dest=${ZDOTDIR:-~}/.zshrc || dest=~/.bashrc
-  append_line $update_config "[ -f ${config_dir}/fzf.${shell} ] && source ${config_dir}/fzf.${shell}" "$dest" "${config_dir}/fzf.${shell}"
+  append_line $update_config "[ -f ${config_base}fzf.${shell} ] && source ${config_base}fzf.${shell}" "$dest" "${config_base}fzf.${shell}"
 done
 
 if [ $key_bindings -eq 1 ] && [[ "$shells" =~ fish ]]; then
-  bind_file=$fish_dir/functions/fish_user_key_bindings.fish
+  bind_file=${fish_dir}functions/fish_user_key_bindings.fish
   if [ ! -e "$bind_file" ]; then
     create_file "$bind_file" \
       'function fish_user_key_bindings' \
